# Generated by Django 5.0.1 on 2024-01-21 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(max_length=64, unique=True)),
                ("content", models.TextField()),
                ("address", models.CharField(max_length=128)),
                ("random", models.BigIntegerField()),
                ("difficulty", models.DecimalField(decimal_places=1, max_digits=3)),
                ("reward", models.DecimalField(decimal_places=6, max_digits=14)),
                ("timestamp", models.DateTimeField()),
            ],
            options={
                "db_table": "blocks",
            },
        ),
        migrations.CreateModel(
            name="PendingTransactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tx_hash", models.CharField(max_length=64, unique=True)),
                ("tx_hex", models.TextField()),
                ("inputs_addresses", models.TextField()),
                ("fees", models.DecimalField(decimal_places=6, max_digits=14)),
                ("propagation_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "pending_transactions",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tx_hash", models.CharField(max_length=64, unique=True)),
                ("tx_hex", models.TextField()),
                ("inputs_addresses", models.TextField()),
                ("outputs_addresses", models.TextField()),
                ("outputs_amounts", models.BigIntegerField()),
                ("fees", models.DecimalField(decimal_places=6, max_digits=14)),
                (
                    "block_hash",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="node.block"
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
            },
        ),
        migrations.CreateModel(
            name="PendingSpentOutputs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("address", models.TextField()),
                (
                    "tx_hash",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="node.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "pending_spent_outputs",
            },
        ),
        migrations.CreateModel(
            name="UnspentOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("address", models.TextField()),
                (
                    "tx_hash",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="node.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "unspent_outputs",
            },
        ),
    ]
